### PR TITLE
Support inspecting Mn v3 applications

### LINKED ISSUE #313: Support Mn 3
This is a meta-ticket to support Marionette v3 with the inspector.

Feel free to edit this ticket to include links to other tickets involved in resolving this.

### PR DESCRIPTION
**Pull request by blikblum**
Fix loading of Mn v3 applications. V2 compatibility kept
Fix #313 #309

### CODE REVIEW

**Comment by jekuno** [comment]
Thanks for your work. I built the extension from `master` branch locally but the UI tab doesn't show any content for my Marionette 3 app. Is this supposed to work already? (The data, radio and activity tabs show content already)

**Comment by blikblum** [comment]
Do you use Application.region?

See   https://github.com/blikblum/marionette-contact-manager for example

**Comment by jekuno** [comment]
Yes, I use `window.app = new Marionette.Application(region: 'main-region')`
and then `app.getRegion().show(myView)`.

Does Inspector rely on using `router.rootRegion = app.getRegion()` in all routers?

**Comment by blikblum** [comment]
No. It should work with just Application.region

Are you using es6 modules?

See caveats

**Comment by jekuno** [comment]
Thanks for pointing me to https://github.com/marionettejs/marionette.inspector#caveats.
I got it working by adding 
```
if (window.__agent) {
  window.__agent.start(Backbone, Marionette);
}
```

👍

**Pull request merged**
